# Tmux config file
# tmux source-file ~/.tmux.conf to reload after changes.

# Mouse Scroll
set -g mouse on
bind -n WheelUpPane   select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \; send-keys -M

# Window buffer
set -g history-limit 50000

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# True colour support (important for Neovim, themes etc.)
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Reload config with prefix + r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
