# Tmux config file
# tmux source-file ~/.tmux.conf to reload after changes.

# On exit, attach to other tmux session if they exist
set -g detach-on-destroy off 

# Mouse Scroll
set -g mouse on

# Window buffer
set -g history-limit 50000

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# True colour support (important for Neovim, themes etc.)
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",ghostty:RGB"
set -ga terminal-features ",ghostty:hyperlinks"

# Reduce key delay
set -sg escape-time 0

# Message display time
set -g display-panes-time 3000
set -g display-time 2000

# Clipboard sync
set -g set-clipboard on

# Reload config with prefix + r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind N command-prompt "new-session -s '%%'"

bind m set -g mouse \; display "Mouse: #{?mouse,ON,OFF}"
